name: Gradle wrapper validation

on:
  push:
    branches: 'master'
    tags-ignore:
      - 'v**'
  pull_request:
    branches: '*'

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
