name: Gradle wrapper validation

on:
  push:
    branches: 'master'
    tags-ignore:
      - 'v**'
  pull_request:
    branches: '*'

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
