# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: TAGGED

on:
  push:
    tags:
      - 'releaseTrigger'

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: trigger by retag
    steps:
      - name: Sanitize Branch
        uses: frabert/replace-string-action@master
        id: gitbranch
        with:
          pattern: 'refs/heads/(.*)'
          string: "${{ github.ref }}"
          replace-with: '$1'
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Perform Release
        uses: eskatos/gradle-command-action@v1
        env:
          GH_REF: ${{ github.ref }}
          GH_EVENT: ${{ toJSON(github.event) }}
        with:
          arguments: tasks

  #     - name: Update Page
  #       uses: eskatos/gradle-command-action@v1
  #       with:
  #         arguments: triggerSiteBuild -P travisApiToken=${{ secrets.TRAVIS_API_TOKEN }} --stacktrace
      
